---
## https://help.sumologic.com/Send_Data/Installed_Collectors/05Reference_Information_for_Collector_Installation/05Set_the_Run_As_User_for_a_Collector

- name: gave read/write access to sumo user
  acl:
    path: "{{ sumologic_collector_root }}"
    entity: "{{ sumologic_collector_user }}"
    etype: user
    permissions: rwx
    recursive: yes
    state: present

- name: check current collector service file
  command: "egrep '^RUN_AS_USER={{ sumologic_collector_user }}' /etc/init.d/collector"
  register: svcfile

- block:
    - name: Remove collector service
      command: "{{ sumologic_collector_root }}/collector remove"
      args:
        removes: /etc/init.d/collector

    - name: configure collector install with sumo user
      replace:
        dest: "{{ sumologic_collector_root }}/collector"
        regexp: '^#RUN_AS_USER=.*'
        replace: "RUN_AS_USER={{ sumologic_collector_user }}"
        backup: yes
    
    - name: Install collector service
      command: "{{ sumologic_collector_root }}/collector install"
      args:
        creates: /etc/init.d/collector
  when: svcfile.stdout == ''
