---

- name: ensure sumo collector requirements packages are present
  package:
    name: "{{ item }}"
    state: present
  register: pkg_result
  until: pkg_result is success
  with_items: "{{ sumocollector_pkg_deps }}"
